log_level                :info
log_location             STDOUT
node_name                'rgrignon'
client_key               'C:/Users/rgrignon/.chef/rgrignon.pem'
validation_client_name   'chef-validator'
validation_key           'C:/Users/rgrignon/chef-validator.pem'
chef_server_url          'https://cent-chef-server'
syntax_check_cache_path  'C:/Users/rgrignon/.chef/syntax_check_cache'
cookbook_path		 'C:/Users/rgrignon/GoogleDrive/git/chef-repo/cookbooks'
